# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{spread3}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tim Lossen"]
  s.date = %q{2009-12-11}
  s.description = %q{portable ruby bindings for the spread3 client api (http://www.spread.org/), built with ffi.}
  s.email = %q{tim@lossen.de}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "example/demo.rb",
     "example/spread.conf",
     "example/start.sh",
     "lib/spread3.rb",
     "lib/spread3/connection.rb",
     "lib/spread3/errors.rb",
     "lib/spread3/ffi.rb",
     "lib/spread3/messages.rb",
     "spread3.gemspec",
     "test/helper.rb",
     "test/test_connection.rb",
     "test/test_connection_no_notify.rb",
     "test/test_errors.rb"
  ]
  s.homepage = %q{http://github.com/tlossen/spread3}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{portable ruby bindings for the spread3 client api}
  s.test_files = [
    "test/helper.rb",
     "test/test_connection.rb",
     "test/test_connection_no_notify.rb",
     "test/test_errors.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

